Resources
itemTypeData
  ^ STON
    fromString:
      '{
    "string_id": "GUI_LIST_TYPE_SOILS",
    "strings": [
      {
        "lang": "english",
        "text": "Soils",
        "plain_text": "Soils"
      },
      {
        "lang": "french",
        "text": "Sols",
        "plain_text": "Sols"
      },
      {
        "lang": "german",
        "text": "Böden",
        "plain_text": "Böden"
      },
      {
        "lang": "italian",
        "text": "Terreni",
        "plain_text": "Terreni"
      },
      {
        "lang": "spanish",
        "text": "Tierras",
        "plain_text": "Tierras"
      }
    ]
  },'