Resources
itemData
  ^ STON fromString: '{
  "url": "https://api.boundlexx.app/api/v1/items/9427/",
  "colors_url": null,
  "sovereign_colors_url": null,
  "game_id": 9427,
  "name": "SOIL_SILTY_COMPACT",
  "string_id": "ITEM_TYPE_SOIL_SILTY_COMPACT",
  "resource_counts_url": null,
  "request_baskets_url": "https://api.boundlexx.app/api/v1/items/9427/shop-stands/",
  "next_request_basket_update": null,
  "shop_stands_url": "https://api.boundlexx.app/api/v1/items/9427/request-baskets/",
  "next_shop_stand_update": null,
  "localization": [
    {
      "lang": "english",
      "name": "Compact Silt"
    },
    {
      "lang": "french",
      "name": "Limon compact"
    },
    {
      "lang": "german",
      "name": "Kompaktierter Schluff"
    },
    {
      "lang": "italian",
      "name": "Sedimenti compatti"
    },
    {
      "lang": "spanish",
      "name": "Cieno compacto"
    }
  ],
  "item_subtitle": {
    "localization": [
      {
        "lang": "english",
        "name": "Common Compacted Block"
      },
      {
        "lang": "german",
        "name": "Gewöhnlicher kompaktierter Block"
      },
      {
        "lang": "french",
        "name": "Bloc compacté commun"
      },
      {
        "lang": "italian",
        "name": "Blocco compresso comune"
      },
      {
        "lang": "spanish",
        "name": "Bloque compacto común"
      }
    ]
  },
  "mint_value": 0.699999988079071,
  "list_type": {
    "string_id": "GUI_LIST_TYPE_SOILS",
    "strings": [
      {
        "lang": "english",
        "text": "Soils",
        "plain_text": "Soils"
      },
      {
        "lang": "french",
        "text": "Sols",
        "plain_text": "Sols"
      },
      {
        "lang": "german",
        "text": "Böden",
        "plain_text": "Böden"
      },
      {
        "lang": "italian",
        "text": "Terreni",
        "plain_text": "Terreni"
      },
      {
        "lang": "spanish",
        "text": "Tierras",
        "plain_text": "Tierras"
      }
    ]
  },
  "description": {
    "string_id": "ITEM_TYPE_SOIL_SILTY_COMPACT_DESCRIPTION",
    "strings": [
      {
        "lang": "english",
        "text": "A compressed block of powdery Soil. Nice and solid, could be a useful Ingredient. ",
        "plain_text": "A compressed block of powdery Soil. Nice and solid, could be a useful Ingredient. "
      },
      {
        "lang": "french",
        "text": "Un bloc de sol poudreux comprimé. Sympa et solide, peut constituer un ingrédient utile. ",
        "plain_text": "Un bloc de sol poudreux comprimé. Sympa et solide, peut constituer un ingrédient utile. "
      },
      {
        "lang": "italian",
        "text": "Un blocco di terreno polveroso compresso. Bello resistente, può essere un utile ingrediente. ",
        "plain_text": "Un blocco di terreno polveroso compresso. Bello resistente, può essere un utile ingrediente. "
      },
      {
        "lang": "german",
        "text": "Ein komprimierter Block aus pulverisiertem Boden. Schön solide und vielleicht eine nützliche Zutat. ",
        "plain_text": "Ein komprimierter Block aus pulverisiertem Boden. Schön solide und vielleicht eine nützliche Zutat. "
      },
      {
        "lang": "spanish",
        "text": "Un Bloque comprimido de tierra polvorienta. Parece sólido, podría ser un ingrediente útil. ",
        "plain_text": "Un Bloque comprimido de tierra polvorienta. Parece sólido, podría ser un ingrediente útil. "
      }
    ]
  }
}'